### ISSUE TITLE
Make it easier to select all folders

### ISSUE THREAD

**Issue by vpetersson** [YippieMove/yippiemove-cli#2]
This is what one is presented with in 'Step 3'. 

```
Please specify the folders you'd like to transfer. For each, if
you'd like to rename the folder, enter a new name. If you'd like
to skip a folder enter 'skip'. To use the existing name, just
press enter.
```

It would be beneficial if we could have an option to 'select all' and avoid having to walk through the entire list of folders.

**Comment by zacharytamas** [comment]
Closed via [this commit](https://github.com/wireload/yippiemove-cli/commit/eed4d91b5693e7dd0b1f16ab1f5a81786a42dfe2).
