### ISSUE TITLE
Folders cannot be named 'skip'

### ISSUE THREAD

**Issue by vpetersson** [YippieMove/yippiemove-cli#4]
Since we are currently using the word 'skip' to deselect a given folder in the folder selection process. If a folder were actually called 'skip', we wouldn't know if were should use the name 'skip' or skip the folder.

**Comment by zacharytamas** [comment]
Closed via [this commit](https://github.com/wireload/yippiemove-cli/commit/eed4d91b5693e7dd0b1f16ab1f5a81786a42dfe2).
